// ============================================================
// ACSON AIRCOND MALAYSIA — Location coverage
//
// One entry per town/suburb we serve. Every entry gets its own
// /{locale}/aircond-acson/{slug} page and a sitemap row, so this list is the
// single source of truth for local SEO coverage. `stateSlug` picks the state
// hero photo out of public/images/locations/.
// ============================================================

export interface LocationEntry {
  slug: string;
  name: string;
  state: string;
  stateSlug: string;
}

export const locations: LocationEntry[] = [
  { slug: 'klcc', name: 'KLCC', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'bangsar', name: 'Bangsar', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'mont-kiara', name: 'Mont Kiara', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'cheras', name: 'Cheras', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'kepong', name: 'Kepong', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'setapak', name: 'Setapak', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'wangsa-maju', name: 'Wangsa Maju', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'sentul', name: 'Sentul', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'bukit-jalil', name: 'Bukit Jalil', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'sri-petaling', name: 'Sri Petaling', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'oug', name: 'OUG', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'taman-desa', name: 'Taman Desa', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'titiwangsa', name: 'Titiwangsa', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'segambut', name: 'Segambut', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'pantai-dalam', name: 'Pantai Dalam', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'dang-wangi', name: 'Dang Wangi', state: 'Kuala Lumpur', stateSlug: 'kuala-lumpur' },
  { slug: 'shah-alam', name: 'Shah Alam', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'petaling-jaya', name: 'Petaling Jaya', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'subang-jaya', name: 'Subang Jaya', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'puchong', name: 'Puchong', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'klang', name: 'Klang', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'cyberjaya', name: 'Cyberjaya', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'putrajaya', name: 'Putrajaya', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'ampang', name: 'Ampang', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'rawang', name: 'Rawang', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'seri-kembangan', name: 'Seri Kembangan', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'bangi', name: 'Bangi', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'kajang', name: 'Kajang', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'semenyih', name: 'Semenyih', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'setia-alam', name: 'Setia Alam', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'kota-damansara', name: 'Kota Damansara', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'damansara', name: 'Damansara', state: 'Selangor', stateSlug: 'selangor' },
  { slug: 'johor-bahru', name: 'Johor Bahru', state: 'Johor', stateSlug: 'johor' },
  { slug: 'iskandar-puteri', name: 'Iskandar Puteri', state: 'Johor', stateSlug: 'johor' },
  { slug: 'kulai', name: 'Kulai', state: 'Johor', stateSlug: 'johor' },
  { slug: 'pontian', name: 'Pontian', state: 'Johor', stateSlug: 'johor' },
  { slug: 'skudai', name: 'Skudai', state: 'Johor', stateSlug: 'johor' },
  { slug: 'pasir-gudang', name: 'Pasir Gudang', state: 'Johor', stateSlug: 'johor' },
  { slug: 'masai', name: 'Masai', state: 'Johor', stateSlug: 'johor' },
  { slug: 'gelang-patah', name: 'Gelang Patah', state: 'Johor', stateSlug: 'johor' },
  { slug: 'senai', name: 'Senai', state: 'Johor', stateSlug: 'johor' },
  { slug: 'kota-tinggi', name: 'Kota Tinggi', state: 'Johor', stateSlug: 'johor' },
  { slug: 'batu-pahat', name: 'Batu Pahat', state: 'Johor', stateSlug: 'johor' },
  { slug: 'muar', name: 'Muar', state: 'Johor', stateSlug: 'johor' },
  { slug: 'kluang', name: 'Kluang', state: 'Johor', stateSlug: 'johor' },
  { slug: 'segamat', name: 'Segamat', state: 'Johor', stateSlug: 'johor' },
  { slug: 'mersing', name: 'Mersing', state: 'Johor', stateSlug: 'johor' },
  { slug: 'george-town', name: 'George Town', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'butterworth', name: 'Butterworth', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'seberang-perai', name: 'Seberang Perai', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'bayan-lepas', name: 'Bayan Lepas', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'jelutong', name: 'Jelutong', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'tanjung-bungah', name: 'Tanjung Bungah', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'gurney', name: 'Gurney', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'air-itam', name: 'Air Itam', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'gelugor', name: 'Gelugor', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'balik-pulau', name: 'Balik Pulau', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'bukit-mertajam', name: 'Bukit Mertajam', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'nibong-tebal', name: 'Nibong Tebal', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'simpang-ampat', name: 'Simpang Ampat', state: 'Penang (Pulau Pinang)', stateSlug: 'penang' },
  { slug: 'ipoh', name: 'Ipoh', state: 'Perak', stateSlug: 'perak' },
  { slug: 'taiping', name: 'Taiping', state: 'Perak', stateSlug: 'perak' },
  { slug: 'sitiawan', name: 'Sitiawan', state: 'Perak', stateSlug: 'perak' },
  { slug: 'lumut', name: 'Lumut', state: 'Perak', stateSlug: 'perak' },
  { slug: 'teluk-intan', name: 'Teluk Intan', state: 'Perak', stateSlug: 'perak' },
  { slug: 'kampar', name: 'Kampar', state: 'Perak', stateSlug: 'perak' },
  { slug: 'batu-gajah', name: 'Batu Gajah', state: 'Perak', stateSlug: 'perak' },
  { slug: 'seri-iskandar', name: 'Seri Iskandar', state: 'Perak', stateSlug: 'perak' },
  { slug: 'tanjung-malim', name: 'Tanjung Malim', state: 'Perak', stateSlug: 'perak' },
  { slug: 'gopeng', name: 'Gopeng', state: 'Perak', stateSlug: 'perak' },
  { slug: 'kuala-kangsar', name: 'Kuala Kangsar', state: 'Perak', stateSlug: 'perak' },
  { slug: 'manjung', name: 'Manjung', state: 'Perak', stateSlug: 'perak' },
  { slug: 'seremban', name: 'Seremban', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'nilai', name: 'Nilai', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'port-dickson', name: 'Port Dickson', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'senawang', name: 'Senawang', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'rembau', name: 'Rembau', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'jelebu', name: 'Jelebu', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'kuala-pilah', name: 'Kuala Pilah', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'tampin', name: 'Tampin', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'mantin', name: 'Mantin', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'rantau', name: 'Rantau', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'labu', name: 'Labu', state: 'Negeri Sembilan', stateSlug: 'negeri-sembilan' },
  { slug: 'melaka-tengah', name: 'Melaka Tengah', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'ayer-keroh', name: 'Ayer Keroh', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'alor-gajah', name: 'Alor Gajah', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'jasin', name: 'Jasin', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'klebang', name: 'Klebang', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'bukit-beruang', name: 'Bukit Beruang', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'bachang', name: 'Bachang', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'cheng', name: 'Cheng', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'batu-berendam', name: 'Batu Berendam', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'durian-tunggal', name: 'Durian Tunggal', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'masjid-tanah', name: 'Masjid Tanah', state: 'Melaka', stateSlug: 'melaka' },
  { slug: 'kuantan', name: 'Kuantan', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'temerloh', name: 'Temerloh', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'bentong', name: 'Bentong', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'raub', name: 'Raub', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'pekan', name: 'Pekan', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'rompin', name: 'Rompin', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'jerantut', name: 'Jerantut', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'maran', name: 'Maran', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'bera', name: 'Bera', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'cameron-highlands', name: 'Cameron Highlands', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'genting-highlands', name: 'Genting Highlands', state: 'Pahang', stateSlug: 'pahang' },
  { slug: 'kota-bharu', name: 'Kota Bharu', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'pasir-mas', name: 'Pasir Mas', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'tumpat', name: 'Tumpat', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'bachok', name: 'Bachok', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'pasir-puteh', name: 'Pasir Puteh', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'machang', name: 'Machang', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'tanah-merah', name: 'Tanah Merah', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'kuala-krai', name: 'Kuala Krai', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'gua-musang', name: 'Gua Musang', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'jeli', name: 'Jeli', state: 'Kelantan', stateSlug: 'kelantan' },
  { slug: 'kuala-terengganu', name: 'Kuala Terengganu', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'kemaman', name: 'Kemaman', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'dungun', name: 'Dungun', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'marang', name: 'Marang', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'setiu', name: 'Setiu', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'besut', name: 'Besut', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'hulu-terengganu', name: 'Hulu Terengganu', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'chukai', name: 'Chukai', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'kerteh', name: 'Kerteh', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'paka', name: 'Paka', state: 'Terengganu', stateSlug: 'terengganu' },
  { slug: 'alor-setar', name: 'Alor Setar', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'sungai-petani', name: 'Sungai Petani', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'kulim', name: 'Kulim', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'langkawi', name: 'Langkawi', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'jitra', name: 'Jitra', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'changlun', name: 'Changlun', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'pendang', name: 'Pendang', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'baling', name: 'Baling', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'yan', name: 'Yan', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'pokok-sena', name: 'Pokok Sena', state: 'Kedah', stateSlug: 'kedah' },
  { slug: 'kota-kinabalu', name: 'Kota Kinabalu', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'sandakan', name: 'Sandakan', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'tawau', name: 'Tawau', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'lahad-datu', name: 'Lahad Datu', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'keningau', name: 'Keningau', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'semporna', name: 'Semporna', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'beaufort', name: 'Beaufort', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'papar', name: 'Papar', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'ranau', name: 'Ranau', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'penampang', name: 'Penampang', state: 'Sabah', stateSlug: 'sabah' },
  { slug: 'kuching', name: 'Kuching', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'miri', name: 'Miri', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'sibu', name: 'Sibu', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'bintulu', name: 'Bintulu', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'limbang', name: 'Limbang', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'sarikei', name: 'Sarikei', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'sri-aman', name: 'Sri Aman', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'kapit', name: 'Kapit', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'mukah', name: 'Mukah', state: 'Sarawak', stateSlug: 'sarawak' },
  { slug: 'serian', name: 'Serian', state: 'Sarawak', stateSlug: 'sarawak' },
];

/** State-level grouping for the coverage index page + footer. */
export const states: { slug: string; name: string; image: string }[] = [
  { slug: 'kuala-lumpur', name: 'Kuala Lumpur', image: '/images/locations/kuala-lumpur.jpg' },
  { slug: 'selangor', name: 'Selangor', image: '/images/locations/selangor.jpg' },
  { slug: 'johor', name: 'Johor', image: '/images/locations/johor.jpg' },
  { slug: 'penang', name: 'Penang (Pulau Pinang)', image: '/images/locations/penang.jpg' },
  { slug: 'perak', name: 'Perak', image: '/images/locations/perak.jpg' },
  { slug: 'negeri-sembilan', name: 'Negeri Sembilan', image: '/images/locations/negeri-sembilan.jpg' },
  { slug: 'melaka', name: 'Melaka', image: '/images/locations/melaka.jpg' },
  { slug: 'pahang', name: 'Pahang', image: '/images/locations/pahang.jpg' },
  { slug: 'kelantan', name: 'Kelantan', image: '/images/locations/kelantan.jpg' },
  { slug: 'terengganu', name: 'Terengganu', image: '/images/locations/terengganu.jpg' },
  { slug: 'kedah', name: 'Kedah', image: '/images/locations/kedah.jpg' },
  { slug: 'sabah', name: 'Sabah', image: '/images/locations/sabah.jpg' },
  { slug: 'sarawak', name: 'Sarawak', image: '/images/locations/sarawak.jpg' },
];

export function locationBySlug(slug: string): LocationEntry | undefined {
  return locations.find((l) => l.slug === slug);
}

export function stateImage(stateSlug: string): string {
  return `/images/locations/${stateSlug}.jpg`;
}

export function locationsInState(stateSlug: string): LocationEntry[] {
  return locations.filter((l) => l.stateSlug === stateSlug);
}
